### PR TITLE
constify libgitrev variables #86

### PR DESCRIPTION
**Pull request by krunal16-c**
- made both the variable constant

### CODE REVIEW

**Comment by dmezh** [comment]
@krunal16-c We can't run CI on this yet. I've opened #88 to fix that; please rebase once that's done.

**Comment by dmezh** [comment]
@krunal16-c Your build is failing; can't approve until it's fixed.

**Comment by krunal16-c** [comment]
in libgitrev.c variables BUILD_GIT_REV AND BUILD_GIT_REV_DIRTY. are not defined.

**Comment by dmezh** [comment]
@krunal16-c, Please take time to familiarize yourself with the code and its purpose; these are not undefined variables. For now, I will remove you as assignee, but please feel free to ping us if you would like to work on something again in the future.

**Pull request closed without merging**
